// Code generated by tui generate. DO NOT EDIT.
// Source: app_new.gsx

package tui

import (
	"context"
	"fmt"

	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/config"
	"github.com/robinojw/dj/internal/api"
	"github.com/robinojw/dj/internal/checkpoint"
	"github.com/robinojw/dj/internal/hooks"
	"github.com/robinojw/dj/internal/modes"
	"github.com/robinojw/dj/internal/tools"
	"github.com/robinojw/dj/internal/tui/theme"
)

type ScreenID int

const (
	ScreenIDChat ScreenID = iota
	ScreenIDTeam
	ScreenIDEnhance
	ScreenIDMCP
	ScreenIDSkills
	ScreenIDCheatSheet
	ScreenIDDiffPager
)

type rootApp struct {
	app            *tui.App
	screen         *tui.State[ScreenID]
	screenStack    []ScreenID
	chatView       *chat
	teamView       *teamScreen
	enhanceView    *enhanceScreen
	mcpView        *mcpManager
	skillsView     *skillBrowser
	cheatSheetView *cheatSheet
	diffPagerView  *diffPager
	permModal      *permissionModal
	turboModal     *turboModal
	debugOverlay   *debugOverlayComponent
	debugMode      *tui.State[bool]

	// Shared state
	mode         *tui.State[modes.ExecutionMode]
	model        *tui.State[string]
	cost         *tui.State[float64]
	inputTokens  *tui.State[int]
	outputTokens *tui.State[int]
	activeMCPs   *tui.State[[]string]

	// Non-TUI dependencies
	t              *theme.Theme
	client         *api.ResponsesClient
	tracker        *api.Tracker
	modeVal        modes.ExecutionMode
	gate           *modes.Gate
	turboConfirmed bool
	checkpoints    *checkpoint.Manager
	toolRegistry   *tools.ToolRegistry
	hooks          *hooks.Runner
	width          int
}

func NewRootApp(
	t *theme.Theme,
	client *api.ResponsesClient,
	tracker *api.Tracker,
	modelName string,
	cfg config.Config,
	toolRegistry *tools.ToolRegistry,
	hookRunner *hooks.Runner,
) *rootApp {
	gate := modes.NewGateWithRegistry(
		modes.ModeConfirm,
		cfg.Execution.Allow.Tools,
		cfg.Execution.Deny.Tools,
		toolRegistry,
	)

	modeState := tui.NewState(modes.ModeConfirm)
	modelState := tui.NewState(modelName)
	costState := tui.NewState(0.0)
	inputTokensState := tui.NewState(0)
	outputTokensState := tui.NewState(0)
	activeMCPsState := tui.NewState([]string{})

	a := &rootApp{
		screen:       tui.NewState(ScreenIDChat),
		mode:         modeState,
		model:        modelState,
		cost:         costState,
		inputTokens:  inputTokensState,
		outputTokens: outputTokensState,
		activeMCPs:   activeMCPsState,
		debugMode:    tui.NewState(false),
		t:            t,
		client:       client,
		tracker:      tracker,
		modeVal:      modes.ModeConfirm,
		gate:         gate,
		checkpoints:  checkpoint.NewManager(20),
		toolRegistry: toolRegistry,
		hooks:        hookRunner,
		width:        80,
	}

	// Create child components with callbacks
	a.chatView = NewChat(t, 80, modeState, modelState, costState, inputTokensState, outputTokensState, activeMCPsState,
		a.handleSubmit, a.openDiffPager)
	a.cheatSheetView = NewCheatSheet(t, a.popScreenFn)
	a.teamView = NewTeamScreen(t, a.popScreenFn)
	a.enhanceView = NewEnhanceScreen(t, a.popScreenFn, nil)
	a.mcpView = NewMCPManager(t, a.popScreenFn, nil)
	a.skillsView = NewSkillBrowser(t, a.popScreenFn)
	a.permModal = NewPermissionModal(t)
	a.turboModal = NewTurboModal(t, a.handleTurboResult)
	a.debugOverlay = NewDebugOverlay(t)

	return a
}

func (a *rootApp) handleSubmit(text string, mentionCtx string) {
	modeCfg := modes.Modes[a.modeVal]

	var toolDefs []api.Tool
	if a.toolRegistry != nil {
		toolDefs = a.toolRegistry.ToolDefinitions(modeCfg.AllowedTools)
	}

	req := api.CreateResponseRequest{
		Model:        a.model.Get(),
		Input:        api.MakeStringInput(text),
		Instructions: modeCfg.SystemPrompt,
		Tools:        toolDefs,
		Reasoning:    &api.Reasoning{Effort: modeCfg.ReasoningEffort},
		Stream:       true,
	}

	if a.debugOverlay.IsVisible() {
		a.debugOverlay.AddInfo(fmt.Sprintf("Starting stream with model: %s", a.model.Get()))
	}

	ctx := context.Background()
	chunks, errs := a.client.Stream(ctx, req)
	a.chatView.StartStream(chunks, errs)
}

func (a *rootApp) openDiffPager(diffs []storedDiff) {
	a.diffPagerView = NewDiffPager(a.t, diffs, a.popScreenFn)
	a.pushScreen(ScreenIDDiffPager)
}

func (a *rootApp) pushScreen(s ScreenID) {
	a.screenStack = append(a.screenStack, a.screen.Get())
	a.screen.Set(s)
	if a.app != nil {
		a.app.EnterAlternateScreen()
	}
}

func (a *rootApp) popScreenFn() {
	if len(a.screenStack) == 0 {
		a.screen.Set(ScreenIDChat)
	} else {
		a.screen.Set(a.screenStack[len(a.screenStack)-1])
		a.screenStack = a.screenStack[:len(a.screenStack)-1]
	}
	if a.app != nil {
		a.app.ExitAlternateScreen()
	}
}

func (a *rootApp) handleTurboResult(confirmed bool) {
	if confirmed {
		a.turboConfirmed = true
		a.modeVal = modes.ModeTurbo
		a.gate.SetMode(modes.ModeTurbo)
		a.mode.Set(modes.ModeTurbo)
	}
}

func (a *rootApp) cycleModel() {
	models := api.CycleModels
	current := -1
	for i, m := range models {
		if m == a.model.Get() {
			current = i
			break
		}
	}
	next := models[(current+1)%len(models)]
	a.model.Set(next)
	if a.tracker != nil {
		a.tracker.SetModel(next)
	}

	if a.debugOverlay.IsVisible() {
		a.debugOverlay.AddInfo("Model switched to " + next)
	}
}

func (a *rootApp) cycleMode() {
	newMode := (a.modeVal + 1) % 3
	if newMode == modes.ModeTurbo && !a.turboConfirmed {
		a.turboModal.Show()
		return
	}
	a.modeVal = newMode
	a.gate.SetMode(newMode)
	a.mode.Set(newMode)
}

func (a *rootApp) KeyMap() tui.KeyMap {
	// Turbo modal intercepts all keys when visible
	if a.turboModal.IsVisible() {
		return a.turboModal.KeyMap()
	}
	// Permission modal intercepts all keys when visible
	if a.permModal.Visible() {
		return a.permModal.KeyMap()
	}

	km := tui.KeyMap{
		tui.OnKey(tui.KeyCtrlC, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyCtrlQ, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.OnKey(tui.KeyCtrlD, func(ke tui.KeyEvent) {
			a.debugOverlay.Toggle()
			a.debugMode.Update(func(v bool) bool { return !v })
		}),
	}

	if a.screen.Get() == ScreenIDChat {
		km = append(km,
			tui.OnKey(tui.KeyCtrlT, func(ke tui.KeyEvent) { a.pushScreen(ScreenIDTeam) }),
			tui.OnKey(tui.KeyCtrlM, func(ke tui.KeyEvent) { a.pushScreen(ScreenIDMCP) }),
			tui.OnKey(tui.KeyCtrlK, func(ke tui.KeyEvent) { a.pushScreen(ScreenIDSkills) }),
			tui.OnKey(tui.KeyCtrlE, func(ke tui.KeyEvent) { a.pushScreen(ScreenIDEnhance) }),
			tui.OnKey(tui.KeyCtrlH, func(ke tui.KeyEvent) { a.pushScreen(ScreenIDCheatSheet) }),
			tui.OnKeyStop(tui.KeyTab, func(ke tui.KeyEvent) { a.cycleMode() }),
			tui.OnKey(tui.KeyCtrlN, func(ke tui.KeyEvent) { a.cycleModel() }),
			tui.OnKey(tui.KeyCtrlZ, func(ke tui.KeyEvent) {
				cp := a.checkpoints.Pop()
				if cp != nil {
					if err := a.checkpoints.Restore(*cp); err == nil {
						a.app.PrintAboveln("[Restored: %s]", cp.Description)
					}
				}
			}),
		)
	}

	return km
}

func (a *rootApp) Render(app *tui.App) *tui.Element {
	var __tui_0 *tui.Element
	if a.turboModal.IsVisible() {
		__tui_1 := a.turboModal.Render(app)
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	} else if a.permModal.Visible() {
		__tui_2 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		)
		__tui_3 := a.permModal.Render(app)
		__tui_2.AddChild(__tui_3)
		__tui_4 := a.chatView.Render(app)
		__tui_2.AddChild(__tui_4)
		if __tui_0 == nil {
			__tui_0 = __tui_2
		}
	} else if a.screen.Get() == ScreenIDChat {
		__tui_5 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		)
		__tui_6 := a.chatView.Render(app)
		__tui_5.AddChild(__tui_6)
		if a.debugOverlay.IsVisible() {
			__tui_7 := a.debugOverlay.Render(app)
			__tui_5.AddChild(__tui_7)
		}
		if __tui_0 == nil {
			__tui_0 = __tui_5
		}
	} else if a.screen.Get() == ScreenIDTeam {
		__tui_8 := a.teamView.Render(app)
		if __tui_0 == nil {
			__tui_0 = __tui_8
		}
	} else if a.screen.Get() == ScreenIDMCP {
		__tui_9 := a.mcpView.Render(app)
		if __tui_0 == nil {
			__tui_0 = __tui_9
		}
	} else if a.screen.Get() == ScreenIDSkills {
		__tui_10 := a.skillsView.Render(app)
		if __tui_0 == nil {
			__tui_0 = __tui_10
		}
	} else if a.screen.Get() == ScreenIDEnhance {
		__tui_11 := a.enhanceView.Render(app)
		if __tui_0 == nil {
			__tui_0 = __tui_11
		}
	} else if a.screen.Get() == ScreenIDCheatSheet {
		__tui_12 := a.cheatSheetView.Render(app)
		if __tui_0 == nil {
			__tui_0 = __tui_12
		}
	} else if a.screen.Get() == ScreenIDDiffPager {
		__tui_13 := a.diffPagerView.Render(app)
		if __tui_0 == nil {
			__tui_0 = __tui_13
		}
	}

	return __tui_0
}

func (a *rootApp) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*rootApp)
	if !ok {
		return
	}
	a.app = f.app
	a.screenStack = f.screenStack
	a.chatView = f.chatView
	a.teamView = f.teamView
	a.enhanceView = f.enhanceView
	a.mcpView = f.mcpView
	a.skillsView = f.skillsView
	a.cheatSheetView = f.cheatSheetView
	a.diffPagerView = f.diffPagerView
	a.permModal = f.permModal
	a.turboModal = f.turboModal
	a.debugOverlay = f.debugOverlay
	a.t = f.t
	a.client = f.client
	a.tracker = f.tracker
	a.modeVal = f.modeVal
	a.gate = f.gate
	a.turboConfirmed = f.turboConfirmed
	a.checkpoints = f.checkpoints
	a.toolRegistry = f.toolRegistry
	a.hooks = f.hooks
	a.width = f.width
}

var _ tui.PropsUpdater = (*rootApp)(nil)

func (a *rootApp) BindApp(app *tui.App) {
	a.app = app
	if a.screen != nil {
		a.screen.BindApp(app)
	}
	if a.debugMode != nil {
		a.debugMode.BindApp(app)
	}
	if a.mode != nil {
		a.mode.BindApp(app)
	}
	if a.model != nil {
		a.model.BindApp(app)
	}
	if a.cost != nil {
		a.cost.BindApp(app)
	}
	if a.inputTokens != nil {
		a.inputTokens.BindApp(app)
	}
	if a.outputTokens != nil {
		a.outputTokens.BindApp(app)
	}
	if a.activeMCPs != nil {
		a.activeMCPs.BindApp(app)
	}
	if binder, ok := any(a.chatView).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
	if binder, ok := any(a.teamView).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
	if binder, ok := any(a.enhanceView).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
	if binder, ok := any(a.mcpView).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
	if binder, ok := any(a.skillsView).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
	if binder, ok := any(a.cheatSheetView).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
	if binder, ok := any(a.diffPagerView).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
	if binder, ok := any(a.permModal).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
	if binder, ok := any(a.turboModal).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
	if binder, ok := any(a.debugOverlay).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
}

var _ tui.AppBinder = (*rootApp)(nil)

func (a *rootApp) UnbindApp() {
	if unbinder, ok := any(a.chatView).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
	if unbinder, ok := any(a.teamView).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
	if unbinder, ok := any(a.enhanceView).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
	if unbinder, ok := any(a.mcpView).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
	if unbinder, ok := any(a.skillsView).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
	if unbinder, ok := any(a.cheatSheetView).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
	if unbinder, ok := any(a.diffPagerView).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
	if unbinder, ok := any(a.permModal).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
	if unbinder, ok := any(a.turboModal).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
	if unbinder, ok := any(a.debugOverlay).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
}

var _ tui.AppUnbinder = (*rootApp)(nil)
