// Code generated by tui generate. DO NOT EDIT.
// Source: chat.gsx

package tui

import (
	"context"
	"strings"
	"time"

	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/agents"
	"github.com/robinojw/dj/internal/api"
	"github.com/robinojw/dj/internal/mentions"
	"github.com/robinojw/dj/internal/modes"
	"github.com/robinojw/dj/internal/tui/theme"
)

type chat struct {
	app           *tui.App
	textareaRef   *tui.Ref
	streamWriter  *tui.StreamWriter
	streaming     *tui.State[bool]
	chatMessages  *tui.State[[]chatMsg]
	eventCh       chan streamEvent
	cancelStream  context.CancelFunc
	apiMessages   []chatMessage
	diffs         []storedDiff
	onSubmit      func(text string, mentionCtx string)
	onOpenDiffs   func(diffs []storedDiff)
	onTitleChange func(title string)
	mode          *tui.State[modes.ExecutionMode]
	model         *tui.State[string]
	cost          *tui.State[float64]
	inputTokens   *tui.State[int]
	outputTokens  *tui.State[int]
	activeMCPs    *tui.State[[]string]
	width         int
	t             *theme.Theme
}

type chatMessage struct {
	Role    string
	Content string
}

func NewChat(
	t *theme.Theme,
	width int,
	mode *tui.State[modes.ExecutionMode],
	model *tui.State[string],
	cost *tui.State[float64],
	inputTokens *tui.State[int],
	outputTokens *tui.State[int],
	activeMCPs *tui.State[[]string],
	onSubmit func(string, string),
	onOpenDiffs func([]storedDiff),
	onTitleChange func(string),
) *chat {
	return &chat{
		textareaRef:   tui.NewRef(),
		streaming:     tui.NewState(false),
		chatMessages:  tui.NewState([]chatMsg{}),
		eventCh:       make(chan streamEvent, 100),
		apiMessages:   make([]chatMessage, 0),
		diffs:         make([]storedDiff, 0),
		onSubmit:      onSubmit,
		onOpenDiffs:   onOpenDiffs,
		onTitleChange: onTitleChange,
		mode:          mode,
		model:         model,
		cost:          cost,
		inputTokens:   inputTokens,
		outputTokens:  outputTokens,
		activeMCPs:    activeMCPs,
		width:         width,
		t:             t,
	}
}

func (c *chat) Init() func() {
	return func() {
		c.cancelActiveStream()
	}
}

func (c *chat) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.NewChannelWatcher(c.eventCh, c.onStreamEvent),
	}
}

func (c *chat) onStreamEvent(ev streamEvent) {
	if !c.streaming.Get() && ev.Type == eventText {
		return
	}

	switch ev.Type {
	case eventText:
		c.chatMessages.Update(func(msgs []chatMsg) []chatMsg {
			lastIsAgent := len(msgs) > 0 && msgs[len(msgs)-1].Kind == chatMsgAgent
			if lastIsAgent {
				msgs[len(msgs)-1].Content += ev.Delta
				return msgs
			}
			return append(msgs, chatMsg{Kind: chatMsgAgent, Content: ev.Delta, Timestamp: time.Now()})
		})
		if c.app != nil {
			if c.streamWriter == nil {
				c.streamWriter = c.app.StreamAbove()
				c.streamWriter.WriteStyled("DJ: ", c.t.TuiPrimaryStyle())
			}
			c.streamWriter.Write([]byte(ev.Delta))
		}

	case eventDone:
		if c.streamWriter != nil {
			c.streamWriter.Close()
			c.streamWriter = nil
		}
		c.inputTokens.Update(func(v int) int { return v + ev.Usage.InputTokens })
		c.outputTokens.Update(func(v int) int { return v + ev.Usage.OutputTokens })
		c.streaming.Set(false)

	case eventError:
		if c.streamWriter != nil {
			c.streamWriter.Close()
			c.streamWriter = nil
		}
		c.chatMessages.Update(func(msgs []chatMsg) []chatMsg {
			return append(msgs, chatMsg{Kind: chatMsgError, Content: ev.Err.Error(), Timestamp: time.Now()})
		})
		if c.app != nil {
			c.app.PrintAboveln("Error: %s", ev.Err.Error())
		}
		c.apiMessages = append(c.apiMessages, chatMessage{Role: "assistant", Content: "Error: " + ev.Err.Error()})
		c.streaming.Set(false)

	case eventDiff:
		c.chatMessages.Update(func(msgs []chatMsg) []chatMsg {
			return append(msgs, chatMsg{
				Kind:      chatMsgDiff,
				FilePath:  ev.FilePath,
				DiffLines: strings.Split(ev.DiffText, "\n"),
				Timestamp: ev.Timestamp,
			})
		})
		summary := formatDiffSummary(ev.FilePath, ev.DiffText)
		if c.app != nil {
			c.app.PrintAboveln("%s", summary)
		}
		c.diffs = append(c.diffs, storedDiff{
			FilePath:  ev.FilePath,
			DiffLines: strings.Split(ev.DiffText, "\n"),
			Timestamp: ev.Timestamp,
		})
	}
}

func (c *chat) submit(text string) {
	text = strings.TrimSpace(text)
	if text == "" || c.streaming.Get() {
		return
	}

	isFirstMessage := len(c.chatMessages.Get()) == 0
	c.chatMessages.Update(func(msgs []chatMsg) []chatMsg {
		return append(msgs, chatMsg{Kind: chatMsgUser, Content: text, Timestamp: time.Now()})
	})
	if c.app != nil {
		c.app.PrintAboveln("You: %s", text)
	}

	if isFirstMessage && c.onTitleChange != nil {
		title := text
		maxTitleLen := 40
		if len(title) > maxTitleLen {
			title = title[:maxTitleLen] + "..."
		}
		c.onTitleChange(title)
	}

	c.apiMessages = append(c.apiMessages, chatMessage{Role: "user", Content: text})
	c.streaming.Set(true)

	parsed := mentions.Parse(text)
	var mentionCtx string
	if len(parsed) > 0 {
		resolved := mentions.Resolve(context.Background(), parsed)
		mentionCtx = mentions.FormatResolved(resolved)
		text = mentions.StripMentions(text)
	}

	c.onSubmit(text, mentionCtx)
}

func (c *chat) StartStream(chunks <-chan api.ResponseChunk, errs <-chan error) {
	c.cancelActiveStream()

	ctx, cancel := context.WithCancel(context.Background())
	c.cancelStream = cancel
	go bridgeStreamToChannel(ctx, chunks, errs, c.eventCh)
}

func (c *chat) cancelActiveStream() {
	if c.cancelStream != nil {
		c.cancelStream()
		c.cancelStream = nil
	}
	if c.streamWriter != nil {
		c.streamWriter.Close()
		c.streamWriter = nil
	}
}

func (c *chat) AppendToolCallBlock(workerID, content string) {
	c.chatMessages.Update(func(msgs []chatMsg) []chatMsg {
		return append(msgs, chatMsg{Kind: chatMsgToolCall, WorkerID: workerID, Content: content, Timestamp: time.Now()})
	})
	if c.app != nil {
		c.app.PrintAboveln("[%s] Tool: %s", workerID, content)
	}
}

func (c *chat) AppendToolResultBlock(workerID, content string) {
	c.chatMessages.Update(func(msgs []chatMsg) []chatMsg {
		return append(msgs, chatMsg{Kind: chatMsgToolResult, WorkerID: workerID, Content: content, Timestamp: time.Now()})
	})
}

func (c *chat) AppendDiffBlock(diff *agents.DiffInfo) {
	c.chatMessages.Update(func(msgs []chatMsg) []chatMsg {
		return append(msgs, chatMsg{
			Kind:      chatMsgDiff,
			FilePath:  diff.FilePath,
			DiffLines: strings.Split(diff.DiffText, "\n"),
			Timestamp: diff.Timestamp,
		})
	})
	summary := formatDiffSummary(diff.FilePath, diff.DiffText)
	if c.app != nil {
		c.app.PrintAboveln("%s", summary)
	}
	c.diffs = append(c.diffs, storedDiff{
		FilePath:  diff.FilePath,
		DiffLines: strings.Split(diff.DiffText, "\n"),
		Timestamp: diff.Timestamp,
	})
}

func (c *chat) LoadSession(session *agents.WorkerSession) {
	msgs := make([]chatMsg, 0, len(session.Turns))
	for _, turn := range session.Turns {
		msgs = append(msgs, sessionTurnToChatMsg(turn))
	}
	c.chatMessages.Set(msgs)
	if c.app != nil {
		for _, turn := range session.Turns {
			switch turn.Kind {
			case agents.TurnText:
				c.app.PrintAboveln("DJ: %s", turn.Content)
			case agents.TurnToolCall:
				c.app.PrintAboveln("[Tool] %s: %s", turn.ToolName, turn.Content)
			case agents.TurnToolResult:
				c.app.PrintAboveln("[Result] %s", truncateMsg(turn.Content, 300))
			}
		}
	}
}

func sessionTurnToChatMsg(turn agents.SessionTurn) chatMsg {
	switch turn.Kind {
	case agents.TurnText:
		return chatMsg{Kind: chatMsgAgent, Content: turn.Content, Timestamp: turn.Timestamp}
	case agents.TurnToolCall:
		return chatMsg{Kind: chatMsgToolCall, ToolName: turn.ToolName, Content: turn.Content, Timestamp: turn.Timestamp}
	case agents.TurnToolResult:
		return chatMsg{Kind: chatMsgToolResult, Content: turn.Content, Timestamp: turn.Timestamp}
	case agents.TurnDiff:
		return chatMsg{Kind: chatMsgDiff, Content: turn.Content, Timestamp: turn.Timestamp}
	case agents.TurnError:
		return chatMsg{Kind: chatMsgError, Content: turn.Content, Timestamp: turn.Timestamp}
	default:
		return chatMsg{Kind: chatMsgSystem, Content: turn.Content, Timestamp: turn.Timestamp}
	}
}

func (c *chat) Messages() []chatMessage {
	return c.apiMessages
}

func (c *chat) KeyMap() tui.KeyMap {
	if c.streaming.Get() {
		return tui.KeyMap{
			tui.OnKey(tui.KeyEscape, func(ke tui.KeyEvent) {
				c.cancelActiveStream()
				c.streaming.Set(false)
			}),
		}
	}

	return tui.KeyMap{
		tui.OnKey(tui.KeyCtrlF, func(ke tui.KeyEvent) {
			if len(c.diffs) > 0 {
				c.onOpenDiffs(c.diffs)
			}
		}),
	}
}

func (c *chat) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
	)
	if c.streaming.Get() {
		__tui_1 := tui.New(
			tui.WithText("Streaming... (Esc to cancel)"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_1)
	}
	__tui_2 := app.MountPersistent(c, 0, func() tui.Component {
		return tui.NewTextArea(
			tui.WithTextAreaAutoFocus(true),
			tui.WithTextAreaPlaceholder("Send a message... (/skills name)"),
			tui.WithTextAreaWidth(c.width-2),
			tui.WithTextAreaBorder(tui.BorderRounded),
			tui.WithTextAreaOnSubmit(c.submit),
		)
	})
	c.textareaRef.Set(__tui_2)
	__tui_0.AddChild(__tui_2)
	__tui_3 := app.Mount(c, 1, func() tui.Component {
		return StatusBar(c.t, c.model.Get(), c.mode.Get(), c.inputTokens.Get(), c.outputTokens.Get(), c.cost.Get(), c.activeMCPs.Get())
	})
	__tui_0.AddChild(__tui_3)

	return __tui_0
}

func (c *chat) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*chat)
	if !ok {
		return
	}
	c.app = f.app
	c.streamWriter = f.streamWriter
	c.cancelStream = f.cancelStream
	c.apiMessages = f.apiMessages
	c.diffs = f.diffs
	c.width = f.width
	c.t = f.t
}

var _ tui.PropsUpdater = (*chat)(nil)

func (c *chat) BindApp(app *tui.App) {
	c.app = app
	if c.streaming != nil {
		c.streaming.BindApp(app)
	}
	if c.chatMessages != nil {
		c.chatMessages.BindApp(app)
	}
	if c.mode != nil {
		c.mode.BindApp(app)
	}
	if c.model != nil {
		c.model.BindApp(app)
	}
	if c.cost != nil {
		c.cost.BindApp(app)
	}
	if c.inputTokens != nil {
		c.inputTokens.BindApp(app)
	}
	if c.outputTokens != nil {
		c.outputTokens.BindApp(app)
	}
	if c.activeMCPs != nil {
		c.activeMCPs.BindApp(app)
	}
}

var _ tui.AppBinder = (*chat)(nil)
