// Code generated by tui generate. DO NOT EDIT.
// Source: chat_render.gsx

package tui

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

func isDiffAdd(line string) bool {
	return strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "+++")
}

func isDiffRemove(line string) bool {
	return strings.HasPrefix(line, "-") && !strings.HasPrefix(line, "---")
}

type RenderChatMsgView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *RenderChatMsgView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *RenderChatMsgView) GetRoot() *tui.Element { return v.Root }

func (v *RenderChatMsgView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *RenderChatMsgView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *RenderChatMsgView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *RenderChatMsgView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*RenderChatMsgView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*RenderChatMsgView)(nil)

var _ tui.AppUnbinder = (*RenderChatMsgView)(nil)

var _ tui.PropsUpdater = (*RenderChatMsgView)(nil)

func RenderChatMsg(t *theme.Theme, msg chatMsg) *RenderChatMsgView {
	var view RenderChatMsgView
	var watchers []tui.Watcher

	var __tui_0 *tui.Element
	if msg.Kind == chatMsgUser {
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithMarginTRBL(1, 0, 1, 0),
		)
		__tui_2 := tui.New(
			tui.WithText("You"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText(msg.Content),
		)
		__tui_1.AddChild(__tui_3)
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	} else if msg.Kind == chatMsgAgent {
		__tui_4 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithMarginTRBL(1, 0, 1, 0),
		)
		__tui_5 := tui.New(
			tui.WithText("DJ"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta).Bold()),
		)
		__tui_4.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText(msg.Content),
		)
		__tui_4.AddChild(__tui_6)
		if __tui_0 == nil {
			__tui_0 = __tui_4
		}
	} else if msg.Kind == chatMsgToolCall {
		__tui_7 := tui.New(
			tui.WithBorder(tui.BorderRounded),
			tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Yellow)),
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithMarginTRBL(1, 0, 1, 0),
		)
		__tui_8 := tui.New(
			tui.WithText("Tool: "+msg.ToolName),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
		)
		__tui_7.AddChild(__tui_8)
		__tui_9 := tui.New(
			tui.WithText(msg.Content),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_7.AddChild(__tui_9)
		if __tui_0 == nil {
			__tui_0 = __tui_7
		}
	} else if msg.Kind == chatMsgToolResult {
		__tui_10 := tui.New(
			tui.WithBorder(tui.BorderRounded),
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithMarginTRBL(1, 0, 1, 0),
		)
		__tui_11 := tui.New(
			tui.WithText("result"),
			tui.WithTextStyle(tui.NewStyle().Dim().Bold()),
		)
		__tui_10.AddChild(__tui_11)
		__tui_12 := tui.New(
			tui.WithText(truncateMsg(msg.Content, 300)),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_10.AddChild(__tui_12)
		if __tui_0 == nil {
			__tui_0 = __tui_10
		}
	} else if msg.Kind == chatMsgDiff {
		__tui_13 := tui.New(
			tui.WithBorder(tui.BorderRounded),
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithPaddingTRBL(0, 1, 0, 1),
			tui.WithMarginTRBL(1, 0, 1, 0),
		)
		__tui_14 := tui.New(
			tui.WithText("  "+msg.FilePath),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
		)
		__tui_13.AddChild(__tui_14)
		for __idx_0, line := range msg.DiffLines {
			_ = __idx_0
			if isDiffAdd(line) {
				__tui_15 := tui.New(
					tui.WithText(line),
					tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green)),
				)
				__tui_13.AddChild(__tui_15)
			} else if isDiffRemove(line) {
				__tui_16 := tui.New(
					tui.WithText(line),
					tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
				)
				__tui_13.AddChild(__tui_16)
			} else {
				__tui_17 := tui.New(
					tui.WithText(line),
					tui.WithTextStyle(tui.NewStyle().Dim()),
				)
				__tui_13.AddChild(__tui_17)
			}
		}
		if __tui_0 == nil {
			__tui_0 = __tui_13
		}
	} else if msg.Kind == chatMsgError {
		__tui_18 := tui.New(
			tui.WithText("Error: "+msg.Content),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
		)
		if __tui_0 == nil {
			__tui_0 = __tui_18
		}
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = RenderChatMsgView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
