// Code generated by tui generate. DO NOT EDIT.
// Source: cheatsheet.gsx

package tui

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

type cheatSheet struct {
	app     *tui.App
	onClose func()
	t       *theme.Theme
}

type shortcut struct {
	Key  string
	Desc string
}

var shortcuts = []shortcut{
	{"Enter", "Send message"},
	{"Ctrl+E", "Enhance prompt"},
	{"Ctrl+T", "Team view"},
	{"Ctrl+K", "Skills browser"},
	{"Ctrl+M", "MCP manager"},
	{"Ctrl+H", "This cheat sheet"},
	{"Ctrl+F", "Diff pager"},
	{"Tab", "Cycle mode (Confirm/Plan/Turbo)"},
	{"Ctrl+N", "Cycle model"},
	{"Ctrl+Z", "Undo (checkpoint)"},
	{"Ctrl+D", "Toggle debug overlay"},
	{"Esc", "Back / dismiss"},
	{"Ctrl+Q", "Quit"},
}

var modeDescs = []shortcut{
	{"Confirm", "Prompts before each tool execution"},
	{"Plan", "Plans actions before executing"},
	{"Turbo", "Executes without confirmation"},
}

func NewCheatSheet(t *theme.Theme, onClose func()) *cheatSheet {
	return &cheatSheet{t: t, onClose: onClose}
}

func (c *cheatSheet) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) {
			c.onClose()
		}),
	}
}

func (c *cheatSheet) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderDouble),
		tui.WithPadding(1),
		tui.WithAlign(tui.AlignCenter),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithHeightPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithText("  dj — Keyboard Shortcuts                 Ctrl+H  "),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithPadding(1),
	)
	for __idx_0, s := range shortcuts {
		_ = __idx_0
		__tui_4 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		)
		__tui_5 := tui.New(
			tui.WithText(s.Key),
			tui.WithWidth(14),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_4.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText(s.Desc),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_4.AddChild(__tui_6)
		__tui_3.AddChild(__tui_4)
	}
	__tui_0.AddChild(__tui_3)
	__tui_7 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithText("  Execution Modes"),
		tui.WithTextStyle(tui.NewStyle().Bold().Foreground(tui.Cyan)),
	)
	__tui_0.AddChild(__tui_8)
	__tui_9 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithPadding(1),
	)
	for __idx_0, m := range modeDescs {
		_ = __idx_0
		__tui_10 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		)
		__tui_11 := tui.New(
			tui.WithText(m.Key),
			tui.WithWidth(14),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_10.AddChild(__tui_11)
		__tui_12 := tui.New(
			tui.WithText(m.Desc),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_10.AddChild(__tui_12)
		__tui_9.AddChild(__tui_10)
	}
	__tui_0.AddChild(__tui_9)
	__tui_13 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_13)
	__tui_14 := tui.New(
		tui.WithText("  [Esc] dismiss"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_14)

	return __tui_0
}

func (c *cheatSheet) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*cheatSheet)
	if !ok {
		return
	}
	c.app = f.app
	c.t = f.t
}

var _ tui.PropsUpdater = (*cheatSheet)(nil)

func (c *cheatSheet) BindApp(app *tui.App) {
	c.app = app
}

var _ tui.AppBinder = (*cheatSheet)(nil)
