// Code generated by tui generate. DO NOT EDIT.
// Source: debug_overlay.gsx

package tui

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

const maxDebugEntries = 50

type DebugEntry struct {
	Time    time.Time
	Level   string // "ERROR", "WARN", "INFO"
	Message string
}

type debugOverlayComponent struct {
	app     *tui.App
	entries *tui.State[[]DebugEntry]
	visible *tui.State[bool]
	t       *theme.Theme
}

func NewDebugOverlay(t *theme.Theme) *debugOverlayComponent {
	return &debugOverlayComponent{
		entries: tui.NewState([]DebugEntry{}),
		visible: tui.NewState(false),
		t:       t,
	}
}

func (d *debugOverlayComponent) Toggle() {
	d.visible.Update(func(v bool) bool { return !v })
}

func (d *debugOverlayComponent) IsVisible() bool {
	return d.visible.Get()
}

func (d *debugOverlayComponent) AddError(msg string) {
	d.add("ERROR", msg)
}

func (d *debugOverlayComponent) AddWarn(msg string) {
	d.add("WARN", msg)
}

func (d *debugOverlayComponent) AddInfo(msg string) {
	d.add("INFO", msg)
}

func (d *debugOverlayComponent) add(level, msg string) {
	d.entries.Update(func(entries []DebugEntry) []DebugEntry {
		entries = append(entries, DebugEntry{
			Time:    time.Now(),
			Level:   level,
			Message: msg,
		})
		if len(entries) > maxDebugEntries {
			entries = entries[len(entries)-maxDebugEntries:]
		}
		return entries
	})
}

func debugLevelClass(level string) string {
	switch level {
	case "ERROR":
		return "text-red font-bold"
	case "WARN":
		return "text-yellow font-bold"
	default:
		return "text-dim"
	}
}

func truncateMsg(msg string, maxLen int) string {
	if len(msg) <= maxLen {
		return msg
	}
	return msg[:maxLen-3] + "..."
}

func (d *debugOverlayComponent) QueueAdd(level, msg string) {
	if d.app != nil {
		d.app.QueueUpdate(func() {
			d.add(level, msg)
		})
	}
}

func (d *debugOverlayComponent) QueueError(msg string) {
	d.QueueAdd("ERROR", msg)
}

func (d *debugOverlayComponent) QueueInfo(format string, args ...any) {
	d.QueueAdd("INFO", fmt.Sprintf(format, args...))
}

func (d *debugOverlayComponent) Render(app *tui.App) *tui.Element {
	var __tui_0 *tui.Element
	if d.visible.Get() {
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithBorder(tui.BorderRounded),
			tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Red)),
			tui.WithPadding(1),
			tui.WithWidthPercent(33.33),
		)
		__tui_2 := tui.New(
			tui.WithText("DEBUG"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithHR(),
		)
		__tui_1.AddChild(__tui_3)
		if len(d.entries.Get()) == 0 {
			__tui_4 := tui.New(
				tui.WithText("No debug messages"),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_1.AddChild(__tui_4)
		} else {
			for __idx_0, entry := range d.entries.Get() {
				_ = __idx_0
				__tui_5 := tui.New(
					tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
				)
				__tui_6 := tui.New(
					tui.WithText(entry.Time.Format("15:04:05")+" "),
					tui.WithTextStyle(tui.NewStyle().Dim()),
				)
				__tui_5.AddChild(__tui_6)
				__tui_7 := tui.New(
					tui.WithText(entry.Level + " "),
				)
				__tui_5.AddChild(__tui_7)
				__tui_8 := tui.New(
					tui.WithText(truncateMsg(entry.Message, 60)),
					tui.WithTextStyle(tui.NewStyle().Dim()),
				)
				__tui_5.AddChild(__tui_8)
				__tui_1.AddChild(__tui_5)
			}
		}
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	}

	return __tui_0
}

func (d *debugOverlayComponent) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*debugOverlayComponent)
	if !ok {
		return
	}
	d.app = f.app
	d.t = f.t
}

var _ tui.PropsUpdater = (*debugOverlayComponent)(nil)

func (d *debugOverlayComponent) BindApp(app *tui.App) {
	d.app = app
	if d.entries != nil {
		d.entries.BindApp(app)
	}
	if d.visible != nil {
		d.visible.BindApp(app)
	}
}

var _ tui.AppBinder = (*debugOverlayComponent)(nil)
