// Code generated by tui generate. DO NOT EDIT.
// Source: diff_pager.gsx

package tui

import (
	"fmt"
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

type diffPager struct {
	app      *tui.App
	diffs    *tui.State[[]storedDiff]
	expanded *tui.State[map[int]bool]
	focused  *tui.State[int]
	scrollY  *tui.State[int]
	onClose  func()
	t        *theme.Theme
}

func NewDiffPager(t *theme.Theme, diffs []storedDiff, onClose func()) *diffPager {
	expandedMap := make(map[int]bool)
	return &diffPager{
		diffs:    tui.NewState(diffs),
		expanded: tui.NewState(expandedMap),
		focused:  tui.NewState(0),
		scrollY:  tui.NewState(0),
		onClose:  onClose,
		t:        t,
	}
}

func (d *diffPager) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) {
			d.onClose()
		}),
		tui.OnKeyStop(tui.KeyTab, func(ke tui.KeyEvent) {
			diffs := d.diffs.Get()
			if len(diffs) > 0 {
				d.focused.Update(func(v int) int { return (v + 1) % len(diffs) })
			}
		}),
		tui.OnKeyModStop(tui.KeyTab, tui.ModShift, func(ke tui.KeyEvent) {
			diffs := d.diffs.Get()
			if len(diffs) > 0 {
				d.focused.Update(func(v int) int {
					v--
					if v < 0 {
						v = len(diffs) - 1
					}
					return v
				})
			}
		}),
		tui.OnKeyStop(tui.KeyEnter, func(ke tui.KeyEvent) {
			idx := d.focused.Get()
			d.expanded.Update(func(m map[int]bool) map[int]bool {
				cp := make(map[int]bool, len(m))
				for k, v := range m {
					cp[k] = v
				}
				cp[idx] = !cp[idx]
				return cp
			})
		}),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) {
			d.scrollY.Update(func(v int) int {
				if v > 0 {
					return v - 1
				}
				return 0
			})
		}),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) {
			d.scrollY.Update(func(v int) int { return v + 1 })
		}),
	}
}

func diffIcon(expanded bool) string {
	if expanded {
		return "▼"
	}
	return "▶"
}

func diffStatsStr(lines []string) string {
	stats := calculateDiffStats(lines)
	return fmt.Sprintf("+%d -%d", stats.additions, stats.deletions)
}

func diffLineClass(line string) string {
	if strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "+++") {
		return "text-green"
	} else if strings.HasPrefix(line, "-") && !strings.HasPrefix(line, "---") {
		return "text-red"
	} else if strings.HasPrefix(line, "@@") {
		return "text-cyan"
	}
	return "text-dim"
}

func (d *diffPager) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("Diff Pager (Tab/Shift+Tab: navigate, Enter: expand, Esc: close)"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_2)
	for i, diff := range d.diffs.Get() {
		_ = i
		if d.focused.Get() == i {
			__tui_3 := tui.New(
				tui.WithText(diffIcon(d.expanded.Get()[i])+" ● "+diff.FilePath+" "+diffStatsStr(diff.DiffLines)),
				tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
			)
			__tui_0.AddChild(__tui_3)
		} else {
			__tui_4 := tui.New(
				tui.WithText(diffIcon(d.expanded.Get()[i])+"   "+diff.FilePath+" "+diffStatsStr(diff.DiffLines)),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_0.AddChild(__tui_4)
		}
		if d.expanded.Get()[i] {
			for __idx_1, line := range diff.DiffLines {
				_ = __idx_1
				__tui_5 := tui.New(
					tui.WithText(line),
				)
				__tui_0.AddChild(__tui_5)
			}
		}
	}

	return __tui_0
}

func (d *diffPager) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*diffPager)
	if !ok {
		return
	}
	d.app = f.app
	d.t = f.t
}

var _ tui.PropsUpdater = (*diffPager)(nil)

func (d *diffPager) BindApp(app *tui.App) {
	d.app = app
	if d.diffs != nil {
		d.diffs.BindApp(app)
	}
	if d.expanded != nil {
		d.expanded.BindApp(app)
	}
	if d.focused != nil {
		d.focused.BindApp(app)
	}
	if d.scrollY != nil {
		d.scrollY.BindApp(app)
	}
}

var _ tui.AppBinder = (*diffPager)(nil)
