// Code generated by tui generate. DO NOT EDIT.
// Source: enhance.gsx

package tui

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

type enhanceScreen struct {
	app      *tui.App
	original *tui.State[string]
	enhanced *tui.State[string]
	loading  *tui.State[bool]
	onClose  func()
	onAccept func(text string)
	t        *theme.Theme
}

func NewEnhanceScreen(t *theme.Theme, onClose func(), onAccept func(string)) *enhanceScreen {
	return &enhanceScreen{
		original: tui.NewState(""),
		enhanced: tui.NewState(""),
		loading:  tui.NewState(false),
		onClose:  onClose,
		onAccept: onAccept,
		t:        t,
	}
}

func (e *enhanceScreen) SetOriginal(text string) {
	e.original.Set(text)
	e.loading.Set(true)
	e.enhanced.Set("")
}

func (e *enhanceScreen) SetEnhanced(text string) {
	e.enhanced.Set(text)
	e.loading.Set(false)
}

func (e *enhanceScreen) KeyMap() tui.KeyMap {
	km := tui.KeyMap{
		tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) {
			e.onClose()
		}),
	}
	if e.enhanced.Get() != "" && !e.loading.Get() {
		km = append(km, tui.OnKeyStop(tui.KeyEnter, func(ke tui.KeyEvent) {
			if e.onAccept != nil {
				e.onAccept(e.enhanced.Get())
			}
		}))
	}
	return km
}

func (e *enhanceScreen) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("  Enhance Prompt                           Ctrl+E  "),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_2)
	if e.loading.Get() {
		__tui_3 := tui.New(
			tui.WithText("  Enhancing prompt..."),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_3)
	} else if e.enhanced.Get() != "" {
		__tui_4 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithPadding(1),
		)
		__tui_5 := tui.New(
			tui.WithText("BEFORE:"),
			tui.WithTextStyle(tui.NewStyle().Dim().Bold()),
		)
		__tui_4.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText(e.original.Get()),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_4.AddChild(__tui_6)
		__tui_7 := tui.New(
			tui.WithHR(),
		)
		__tui_4.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithText("AFTER:"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_4.AddChild(__tui_8)
		__tui_9 := tui.New(
			tui.WithText(e.enhanced.Get()),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_4.AddChild(__tui_9)
		__tui_0.AddChild(__tui_4)
	} else {
		__tui_10 := tui.New(
			tui.WithText("  Type a prompt in chat, then press Ctrl+E to enhance it."),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_10)
	}
	__tui_11 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithText("  [Enter] use enhanced  [Esc] keep original"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_12)

	return __tui_0
}

func (e *enhanceScreen) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*enhanceScreen)
	if !ok {
		return
	}
	e.app = f.app
	e.t = f.t
}

var _ tui.PropsUpdater = (*enhanceScreen)(nil)

func (e *enhanceScreen) BindApp(app *tui.App) {
	e.app = app
	if e.original != nil {
		e.original.BindApp(app)
	}
	if e.enhanced != nil {
		e.enhanced.BindApp(app)
	}
	if e.loading != nil {
		e.loading.BindApp(app)
	}
}

var _ tui.AppBinder = (*enhanceScreen)(nil)
