// Code generated by tui generate. DO NOT EDIT.
// Source: mcp.gsx

package tui

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

type MCPServerInfo struct {
	Name      string
	Type      string // "stdio", "http", "sse"
	ToolCount int
	Active    bool
}

type mcpManager struct {
	app      *tui.App
	servers  *tui.State[[]MCPServerInfo]
	selected *tui.State[int]
	onClose  func()
	onToggle func(name string, active bool)
	t        *theme.Theme
}

func NewMCPManager(t *theme.Theme, onClose func(), onToggle func(string, bool)) *mcpManager {
	return &mcpManager{
		servers:  tui.NewState([]MCPServerInfo{}),
		selected: tui.NewState(0),
		onClose:  onClose,
		onToggle: onToggle,
		t:        t,
	}
}

func (m *mcpManager) SetServers(servers []MCPServerInfo) {
	m.servers.Set(servers)
}

func (m *mcpManager) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) {
			m.onClose()
		}),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) {
			m.selected.Update(func(v int) int {
				if v > 0 {
					return v - 1
				}
				return 0
			})
		}),
		tui.OnRuneStop('k', func(ke tui.KeyEvent) {
			m.selected.Update(func(v int) int {
				if v > 0 {
					return v - 1
				}
				return 0
			})
		}),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) {
			servers := m.servers.Get()
			m.selected.Update(func(v int) int {
				if v < len(servers)-1 {
					return v + 1
				}
				return v
			})
		}),
		tui.OnRuneStop('j', func(ke tui.KeyEvent) {
			servers := m.servers.Get()
			m.selected.Update(func(v int) int {
				if v < len(servers)-1 {
					return v + 1
				}
				return v
			})
		}),
		tui.OnKeyStop(tui.KeyEnter, func(ke tui.KeyEvent) {
			servers := m.servers.Get()
			idx := m.selected.Get()
			if idx < len(servers) {
				srv := servers[idx]
				if m.onToggle != nil {
					m.onToggle(srv.Name, !srv.Active)
				}
			}
		}),
	}
}

func mcpStatusIcon(active bool) string {
	if active {
		return "● ✓"
	}
	return "○ ✗"
}

func (m *mcpManager) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("  MCP Servers                              Ctrl+M  "),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_2)
	if len(m.servers.Get()) == 0 {
		__tui_3 := tui.New(
			tui.WithText("  No MCP servers configured."),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_3)
	} else {
		for i, srv := range m.servers.Get() {
			_ = i
			if m.selected.Get() == i {
				__tui_4 := tui.New(
					tui.WithText(fmt.Sprintf("  %s %s [%s] %d tools", mcpStatusIcon(srv.Active), srv.Name, srv.Type, srv.ToolCount)),
					tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
				)
				__tui_0.AddChild(__tui_4)
			} else {
				__tui_5 := tui.New(
					tui.WithText(fmt.Sprintf("  %s %s [%s] %d tools", mcpStatusIcon(srv.Active), srv.Name, srv.Type, srv.ToolCount)),
					tui.WithTextStyle(tui.NewStyle().Dim()),
				)
				__tui_0.AddChild(__tui_5)
			}
		}
	}
	__tui_6 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithText("  [Enter] toggle  [↑/↓] navigate  [Esc] back"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_7)

	return __tui_0
}

func (m *mcpManager) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*mcpManager)
	if !ok {
		return
	}
	m.app = f.app
	m.t = f.t
}

var _ tui.PropsUpdater = (*mcpManager)(nil)

func (m *mcpManager) BindApp(app *tui.App) {
	m.app = app
	if m.servers != nil {
		m.servers.BindApp(app)
	}
	if m.selected != nil {
		m.selected.BindApp(app)
	}
}

var _ tui.AppBinder = (*mcpManager)(nil)
