// Code generated by tui generate. DO NOT EDIT.
// Source: permission_modal.gsx

package tui

import (
	"fmt"
	"sort"
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/modes"
	"github.com/robinojw/dj/internal/tui/theme"
)

type permissionModal struct {
	app     *tui.App
	request *tui.State[*modes.PermissionRequest]
	scope   *tui.State[modes.RememberScope]
	t       *theme.Theme
}

func NewPermissionModal(t *theme.Theme) *permissionModal {
	return &permissionModal{
		request: tui.NewState[*modes.PermissionRequest](nil),
		scope:   tui.NewState(modes.RememberOnce),
		t:       t,
	}
}

func (p *permissionModal) Show(req *modes.PermissionRequest) {
	p.request.Set(req)
	p.scope.Set(modes.RememberOnce)
	if p.app != nil {
		p.app.SetInlineHeight(10)
	}
}

func (p *permissionModal) dismiss() {
	p.request.Set(nil)
	if p.app != nil {
		p.app.SetInlineHeight(3)
	}
}

func (p *permissionModal) Visible() bool {
	return p.request.Get() != nil
}

func (p *permissionModal) KeyMap() tui.KeyMap {
	if p.request.Get() == nil {
		return nil
	}
	return tui.KeyMap{
		tui.OnRuneStop('y', func(ke tui.KeyEvent) {
			req := p.request.Get()
			if req != nil && req.RespCh != nil {
				req.RespCh <- modes.PermissionResp{Allowed: true, RememberFor: p.scope.Get()}
			}
			p.dismiss()
		}),
		tui.OnRuneStop('n', func(ke tui.KeyEvent) {
			req := p.request.Get()
			if req != nil && req.RespCh != nil {
				req.RespCh <- modes.PermissionResp{Allowed: false}
			}
			p.dismiss()
		}),
		tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) {
			req := p.request.Get()
			if req != nil && req.RespCh != nil {
				req.RespCh <- modes.PermissionResp{Allowed: false}
			}
			p.dismiss()
		}),
		tui.OnKeyStop(tui.KeyTab, func(ke tui.KeyEvent) {
			p.scope.Update(func(s modes.RememberScope) modes.RememberScope {
				return (s + 1) % 3
			})
		}),
	}
}

func (p *permissionModal) scopeLabel() string {
	s := p.scope.Get()
	once := scopeStr("Once", s == modes.RememberOnce)
	session := scopeStr("Session", s == modes.RememberSession)
	always := scopeStr("Always", s == modes.RememberAlways)
	return "Scope: " + once + " │ " + session + " │ " + always
}

func scopeStr(label string, selected bool) string {
	if selected {
		return "[" + label + "]"
	}
	return label
}

func formatPermArgs(args map[string]any) string {
	keys := make([]string, 0, len(args))
	for k := range args {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var parts []string
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("%s=%v", k, args[k]))
	}
	return strings.Join(parts, ", ")
}

func (p *permissionModal) Render(app *tui.App) *tui.Element {
	var __tui_0 *tui.Element
	if p.request.Get() != nil {
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithBorder(tui.BorderRounded),
			tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Yellow)),
			tui.WithPadding(1),
		)
		__tui_2 := tui.New(
			tui.WithText("🔒 Permission Required"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText("Tool: "+p.request.Get().Tool),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
		)
		__tui_1.AddChild(__tui_3)
		if len(p.request.Get().Args) > 0 {
			__tui_4 := tui.New(
				tui.WithText(formatPermArgs(p.request.Get().Args)),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_1.AddChild(__tui_4)
		}
		__tui_5 := tui.New(
			tui.WithText(p.scopeLabel()),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText("[y] allow  [n/Esc] deny  [Tab] scope"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_6)
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	}

	return __tui_0
}

func (p *permissionModal) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*permissionModal)
	if !ok {
		return
	}
	p.app = f.app
	p.t = f.t
}

var _ tui.PropsUpdater = (*permissionModal)(nil)

func (p *permissionModal) BindApp(app *tui.App) {
	p.app = app
	if p.request != nil {
		p.request.BindApp(app)
	}
	if p.scope != nil {
		p.scope.BindApp(app)
	}
}

var _ tui.AppBinder = (*permissionModal)(nil)
