// Code generated by tui generate. DO NOT EDIT.
// Source: skills.gsx

package tui

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

type SkillInfo struct {
	Name        string
	Description string
	Source      string // "builtin", "project", "user"
	Implicit    bool
}

type skillBrowser struct {
	app      *tui.App
	skills   *tui.State[[]SkillInfo]
	selected *tui.State[int]
	onClose  func()
	t        *theme.Theme
}

func NewSkillBrowser(t *theme.Theme, onClose func()) *skillBrowser {
	return &skillBrowser{
		skills:   tui.NewState([]SkillInfo{}),
		selected: tui.NewState(0),
		onClose:  onClose,
		t:        t,
	}
}

func (s *skillBrowser) SetSkills(skills []SkillInfo) {
	s.skills.Set(skills)
}

func (s *skillBrowser) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) {
			s.onClose()
		}),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) {
			s.selected.Update(func(v int) int {
				if v > 0 {
					return v - 1
				}
				return 0
			})
		}),
		tui.OnRuneStop('k', func(ke tui.KeyEvent) {
			s.selected.Update(func(v int) int {
				if v > 0 {
					return v - 1
				}
				return 0
			})
		}),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) {
			skills := s.skills.Get()
			s.selected.Update(func(v int) int {
				if v < len(skills)-1 {
					return v + 1
				}
				return v
			})
		}),
		tui.OnRuneStop('j', func(ke tui.KeyEvent) {
			skills := s.skills.Get()
			s.selected.Update(func(v int) int {
				if v < len(skills)-1 {
					return v + 1
				}
				return v
			})
		}),
	}
}

func implicitIcon(implicit bool) string {
	if implicit {
		return "⚡"
	}
	return " "
}

func (s *skillBrowser) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("  Skills Library                           Ctrl+K  "),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_2)
	if len(s.skills.Get()) == 0 {
		__tui_3 := tui.New(
			tui.WithText("  No skills loaded."),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_3)
	} else {
		for i, skill := range s.skills.Get() {
			_ = i
			if s.selected.Get() == i {
				__tui_4 := tui.New(
					tui.WithText(implicitIcon(skill.Implicit)+" /"+skill.Name+" ["+skill.Source+"] "+skill.Description),
					tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
				)
				__tui_0.AddChild(__tui_4)
			} else {
				__tui_5 := tui.New(
					tui.WithText(implicitIcon(skill.Implicit)+" /"+skill.Name+" ["+skill.Source+"] "+skill.Description),
					tui.WithTextStyle(tui.NewStyle().Dim()),
				)
				__tui_0.AddChild(__tui_5)
			}
		}
	}
	__tui_6 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithText("  [/name] invoke in chat  [↑/↓] navigate  [Esc] back"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_7)

	return __tui_0
}

func (s *skillBrowser) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*skillBrowser)
	if !ok {
		return
	}
	s.app = f.app
	s.t = f.t
}

var _ tui.PropsUpdater = (*skillBrowser)(nil)

func (s *skillBrowser) BindApp(app *tui.App) {
	s.app = app
	if s.skills != nil {
		s.skills.BindApp(app)
	}
	if s.selected != nil {
		s.selected.BindApp(app)
	}
}

var _ tui.AppBinder = (*skillBrowser)(nil)
