// Code generated by tui generate. DO NOT EDIT.
// Source: statusbar.gsx

package tui

import (
	"fmt"
	"strings"

	"github.com/dustin/go-humanize"
	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/modes"
	"github.com/robinojw/dj/internal/tui/theme"
)

func modeLabel(mode modes.ExecutionMode) string {
	switch mode {
	case modes.ModeTurbo:
		return "Turbo"
	case modes.ModePlan:
		return "Plan"
	default:
		return "Confirm"
	}
}

func modeClass(mode modes.ExecutionMode) string {
	switch mode {
	case modes.ModeTurbo:
		return "text-red font-bold"
	case modes.ModePlan:
		return "text-blue font-bold"
	default:
		return "text-yellow font-bold"
	}
}

func formatTokens(input, output int) string {
	return humanize.Comma(int64(input)) + "/" + humanize.Comma(int64(output))
}

type StatusBarView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *StatusBarView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *StatusBarView) GetRoot() *tui.Element { return v.Root }

func (v *StatusBarView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *StatusBarView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *StatusBarView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *StatusBarView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*StatusBarView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*StatusBarView)(nil)

var _ tui.AppUnbinder = (*StatusBarView)(nil)

var _ tui.PropsUpdater = (*StatusBarView)(nil)

func StatusBar(t *theme.Theme, model string, mode modes.ExecutionMode, inputTokens int, outputTokens int, cost float64, activeMCPs []string) *StatusBarView {
	var view StatusBarView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
	)
	__tui_1 := tui.New(
		tui.WithText("● "+model),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(" │ "),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(modeLabel(mode)),
	)
	__tui_0.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText(" │ "),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(formatTokens(inputTokens, outputTokens)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText(" │ $"+fmt.Sprintf("%.4f", cost)),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_6)
	if len(activeMCPs) > 0 {
		__tui_7 := tui.New(
			tui.WithText(" │ MCP: "+strings.Join(activeMCPs, ", ")),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_7)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = StatusBarView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
