// Code generated by tui generate. DO NOT EDIT.
// Source: team.gsx

package tui

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

type AgentStatus struct {
	ID       string
	Name     string
	Status   string
	ParentID string
	Output   string
}

type teamScreen struct {
	app         *tui.App
	agents      *tui.State[[]AgentStatus]
	cursor      *tui.State[cursorPos]
	onClose     func()
	onOpenAgent func(agentID string)
	onSplitView func()
	t           *theme.Theme
}

func NewTeamScreen(t *theme.Theme, onClose func(), onOpenAgent func(string), onSplitView func()) *teamScreen {
	return &teamScreen{
		agents:      tui.NewState([]AgentStatus{}),
		cursor:      tui.NewState(cursorPos{}),
		onClose:     onClose,
		onOpenAgent: onOpenAgent,
		onSplitView: onSplitView,
		t:           t,
	}
}

func (s *teamScreen) SetAgents(agents []AgentStatus) {
	s.agents.Set(agents)
}

func (s *teamScreen) SetAgentStatus(workerID, status string) {
	s.agents.Update(func(agents []AgentStatus) []AgentStatus {
		for i, agent := range agents {
			if agent.ID == workerID {
				agents[i].Status = status
			}
		}
		return agents
	})
}

func (s *teamScreen) AppendAgentDelta(workerID, delta string) {
	s.agents.Update(func(agents []AgentStatus) []AgentStatus {
		for i, agent := range agents {
			if agent.ID == workerID {
				agents[i].Output += delta
				if agents[i].Status != "running" {
					agents[i].Status = "running"
				}
			}
		}
		return agents
	})
}

func (s *teamScreen) AppendToolCall(workerID, content string) {
	s.agents.Update(func(agents []AgentStatus) []AgentStatus {
		for i, agent := range agents {
			if agent.ID == workerID {
				agents[i].Output += "\n[Tool] " + content
			}
		}
		return agents
	})
}

func (s *teamScreen) AppendToolResult(workerID, content string) {
	s.agents.Update(func(agents []AgentStatus) []AgentStatus {
		for i, agent := range agents {
			if agent.ID == workerID {
				agents[i].Output += "\n[Result] " + content
			}
		}
		return agents
	})
}

func agentStatusIcon(status string) string {
	switch status {
	case "running":
		return ">"
	case "completed":
		return "+"
	case "error":
		return "!"
	case "skipped":
		return "-"
	default:
		return "."
	}
}

func (s *teamScreen) cursorAgentID() string {
	layers := buildDAGLayers(s.agents.Get())
	pos := s.cursor.Get()
	if pos.Col < len(layers) && pos.Row < len(layers[pos.Col]) {
		return layers[pos.Col][pos.Row].ID
	}
	return ""
}

func (s *teamScreen) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) { s.onClose() }),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) {
			s.cursor.Update(func(p cursorPos) cursorPos {
				if p.Row > 0 {
					p.Row--
				}
				return p
			})
		}),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) {
			layers := buildDAGLayers(s.agents.Get())
			s.cursor.Update(func(p cursorPos) cursorPos {
				if p.Col < len(layers) {
					maxRow := len(layers[p.Col]) - 1
					if p.Row < maxRow {
						p.Row++
					}
				}
				return p
			})
		}),
		tui.OnKey(tui.KeyLeft, func(ke tui.KeyEvent) {
			s.cursor.Update(func(p cursorPos) cursorPos {
				if p.Col > 0 {
					p.Col--
					p.Row = 0
				}
				return p
			})
		}),
		tui.OnKey(tui.KeyRight, func(ke tui.KeyEvent) {
			layers := buildDAGLayers(s.agents.Get())
			s.cursor.Update(func(p cursorPos) cursorPos {
				if p.Col < len(layers)-1 {
					p.Col++
					p.Row = 0
				}
				return p
			})
		}),
		tui.OnKeyStop(tui.KeyEnter, func(ke tui.KeyEvent) {
			if agentID := s.cursorAgentID(); agentID != "" && s.onOpenAgent != nil {
				s.onOpenAgent(agentID)
			}
		}),
		tui.OnRuneStop('/', func(ke tui.KeyEvent) {
			if s.onSplitView != nil {
				s.onSplitView()
			}
		}),
		tui.OnRuneStop('k', func(ke tui.KeyEvent) {
			s.cursor.Update(func(p cursorPos) cursorPos {
				if p.Row > 0 {
					p.Row--
				}
				return p
			})
		}),
		tui.OnRuneStop('j', func(ke tui.KeyEvent) {
			layers := buildDAGLayers(s.agents.Get())
			s.cursor.Update(func(p cursorPos) cursorPos {
				if p.Col < len(layers) {
					maxRow := len(layers[p.Col]) - 1
					if p.Row < maxRow {
						p.Row++
					}
				}
				return p
			})
		}),
		tui.OnRuneStop('h', func(ke tui.KeyEvent) {
			s.cursor.Update(func(p cursorPos) cursorPos {
				if p.Col > 0 {
					p.Col--
					p.Row = 0
				}
				return p
			})
		}),
		tui.OnRuneStop('l', func(ke tui.KeyEvent) {
			layers := buildDAGLayers(s.agents.Get())
			s.cursor.Update(func(p cursorPos) cursorPos {
				if p.Col < len(layers)-1 {
					p.Col++
					p.Row = 0
				}
				return p
			})
		}),
	}
}

func agentLabel(agent AgentStatus) string {
	return fmt.Sprintf("[%s] %s (%s)", agentStatusIcon(agent.Status), agent.Name, agent.Status)
}

func (s *teamScreen) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("  Team View  (Enter: open session  /: split  Esc: back)"),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_2)
	if len(s.agents.Get()) == 0 {
		__tui_3 := tui.New(
			tui.WithText("  No agents running."),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_3)
	} else {
		__tui_4 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithGap(4),
			tui.WithFlexGrow(1), tui.WithFlexShrink(1),
		)
		for col, layer := range buildDAGLayers(s.agents.Get()) {
			_ = col
			__tui_5 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
				tui.WithGap(1),
			)
			for row, agent := range layer {
				_ = row
				if s.cursor.Get().Col == col && s.cursor.Get().Row == row {
					__tui_6 := tui.New(
						tui.WithBorder(tui.BorderRounded),
						tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
						tui.WithPadding(1),
						tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
						tui.WithWidth(24),
					)
					__tui_7 := tui.New(
						tui.WithText(agent.Name),
						tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
					)
					__tui_6.AddChild(__tui_7)
					__tui_8 := tui.New(
						tui.WithText(agentStatusIcon(agent.Status)+" "+agent.Status),
						tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
					)
					__tui_6.AddChild(__tui_8)
					__tui_5.AddChild(__tui_6)
				} else {
					__tui_9 := tui.New(
						tui.WithBorder(tui.BorderRounded),
						tui.WithPadding(1),
						tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
						tui.WithWidth(24),
					)
					__tui_10 := tui.New(
						tui.WithText(agent.Name),
						tui.WithTextStyle(tui.NewStyle().Bold()),
					)
					__tui_9.AddChild(__tui_10)
					__tui_11 := tui.New(
						tui.WithText(agentStatusIcon(agent.Status)+" "+agent.Status),
						tui.WithTextStyle(tui.NewStyle().Dim()),
					)
					__tui_9.AddChild(__tui_11)
					__tui_5.AddChild(__tui_9)
				}
			}
			__tui_4.AddChild(__tui_5)
		}
		__tui_0.AddChild(__tui_4)
	}
	__tui_12 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_12)
	__tui_13 := tui.New(
		tui.WithText("  [h/l] columns  [j/k] rows  [Enter] open  [/] split"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_13)

	return __tui_0
}

func (s *teamScreen) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*teamScreen)
	if !ok {
		return
	}
	s.app = f.app
	s.t = f.t
}

var _ tui.PropsUpdater = (*teamScreen)(nil)

func (s *teamScreen) BindApp(app *tui.App) {
	s.app = app
	if s.agents != nil {
		s.agents.BindApp(app)
	}
	if s.cursor != nil {
		s.cursor.BindApp(app)
	}
}

var _ tui.AppBinder = (*teamScreen)(nil)
