// Code generated by tui generate. DO NOT EDIT.
// Source: team.gsx

package tui

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

type AgentStatus struct {
	ID       string
	Name     string
	Status   string // "running", "idle", "completed", "error", "skipped"
	ParentID string
	Output   string
}

type teamScreen struct {
	app      *tui.App
	agents   *tui.State[[]AgentStatus]
	selected *tui.State[int]
	onClose  func()
	t        *theme.Theme
}

func NewTeamScreen(t *theme.Theme, onClose func()) *teamScreen {
	return &teamScreen{
		agents:   tui.NewState([]AgentStatus{}),
		selected: tui.NewState(0),
		onClose:  onClose,
		t:        t,
	}
}

func (s *teamScreen) SetAgents(agents []AgentStatus) {
	s.agents.Set(agents)
}

func agentStatusIcon(status string) string {
	switch status {
	case "running":
		return "⏳"
	case "completed":
		return "✅"
	case "error":
		return "❌"
	case "skipped":
		return "⏭️"
	default:
		return "💤"
	}
}

func (s *teamScreen) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) {
			s.onClose()
		}),
		tui.OnKey(tui.KeyUp, func(ke tui.KeyEvent) {
			s.selected.Update(func(v int) int {
				if v > 0 {
					return v - 1
				}
				return 0
			})
		}),
		tui.OnRuneStop('k', func(ke tui.KeyEvent) {
			s.selected.Update(func(v int) int {
				if v > 0 {
					return v - 1
				}
				return 0
			})
		}),
		tui.OnKey(tui.KeyDown, func(ke tui.KeyEvent) {
			agents := s.agents.Get()
			s.selected.Update(func(v int) int {
				if v < len(agents)-1 {
					return v + 1
				}
				return v
			})
		}),
		tui.OnRuneStop('j', func(ke tui.KeyEvent) {
			agents := s.agents.Get()
			s.selected.Update(func(v int) int {
				if v < len(agents)-1 {
					return v + 1
				}
				return v
			})
		}),
	}
}

func (s *teamScreen) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
	)
	__tui_1 := tui.New(
		tui.WithText("  Team View                                Ctrl+T  "),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_2)
	if len(s.agents.Get()) == 0 {
		__tui_3 := tui.New(
			tui.WithText("  No agents running. Start a complex task to see the team view."),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_0.AddChild(__tui_3)
	} else {
		__tui_4 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		)
		for i, agent := range s.agents.Get() {
			_ = i
			if s.selected.Get() == i {
				__tui_5 := tui.New(
					tui.WithText("● "+agentStatusIcon(agent.Status)+" "+agent.Name+" ["+agent.Status+"]"),
					tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
				)
				__tui_4.AddChild(__tui_5)
			} else {
				__tui_6 := tui.New(
					tui.WithText("  "+agentStatusIcon(agent.Status)+" "+agent.Name+" ["+agent.Status+"]"),
					tui.WithTextStyle(tui.NewStyle().Dim()),
				)
				__tui_4.AddChild(__tui_6)
			}
		}
		__tui_0.AddChild(__tui_4)
		__tui_7 := tui.New(
			tui.WithHR(),
		)
		__tui_0.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		)
		__tui_9 := tui.New(
			tui.WithText("Output:"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
		)
		__tui_8.AddChild(__tui_9)
		if s.selected.Get() < len(s.agents.Get()) {
			__tui_10 := tui.New(
				tui.WithText(s.agents.Get()[s.selected.Get()].Output),
				tui.WithTextStyle(tui.NewStyle().Dim()),
			)
			__tui_8.AddChild(__tui_10)
		}
		__tui_0.AddChild(__tui_8)
	}
	__tui_11 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_11)
	__tui_12 := tui.New(
		tui.WithText("  [↑/↓] navigate  [Esc] back"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_12)

	return __tui_0
}

func (s *teamScreen) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*teamScreen)
	if !ok {
		return
	}
	s.app = f.app
	s.t = f.t
}

var _ tui.PropsUpdater = (*teamScreen)(nil)

func (s *teamScreen) BindApp(app *tui.App) {
	s.app = app
	if s.agents != nil {
		s.agents.BindApp(app)
	}
	if s.selected != nil {
		s.selected.BindApp(app)
	}
}

var _ tui.AppBinder = (*teamScreen)(nil)
