// Code generated by tui generate. DO NOT EDIT.
// Source: topbar.gsx

package tui

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

type topBar struct {
	branch *tui.State[string]
	cwd    *tui.State[string]
	title  *tui.State[string]
	t      *theme.Theme
}

func NewTopBar(t *theme.Theme, branch, cwd, title *tui.State[string]) *topBar {
	return &topBar{branch: branch, cwd: cwd, title: title, t: t}
}

func (b *topBar) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifySpaceBetween),
		tui.WithFlexShrink(0),
		tui.WithPaddingTRBL(0, 1, 0, 1),
	)
	__tui_1 := tui.New(
		tui.WithText(b.title.Get()),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(b.branch.Get()+"  "+b.cwd.Get()),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_0.AddChild(__tui_2)

	return __tui_0
}

func (b *topBar) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*topBar)
	if !ok {
		return
	}
	b.t = f.t
}

var _ tui.PropsUpdater = (*topBar)(nil)

func (b *topBar) BindApp(app *tui.App) {
	if b.branch != nil {
		b.branch.BindApp(app)
	}
	if b.cwd != nil {
		b.cwd.BindApp(app)
	}
	if b.title != nil {
		b.title.BindApp(app)
	}
}

var _ tui.AppBinder = (*topBar)(nil)
