// Code generated by tui generate. DO NOT EDIT.
// Source: turbo_modal.gsx

package tui

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/robinojw/dj/internal/tui/theme"
)

type turboModal struct {
	app       *tui.App
	visible   *tui.State[bool]
	confirmed *tui.State[bool]
	onResult  func(confirmed bool)
	t         *theme.Theme
}

func NewTurboModal(t *theme.Theme, onResult func(bool)) *turboModal {
	return &turboModal{
		visible:   tui.NewState(false),
		confirmed: tui.NewState(false),
		onResult:  onResult,
		t:         t,
	}
}

func (m *turboModal) Show() {
	m.visible.Set(true)
	if m.app != nil {
		m.app.SetInlineHeight(10)
	}
}

func (m *turboModal) IsVisible() bool {
	return m.visible.Get()
}

func (m *turboModal) IsConfirmed() bool {
	return m.confirmed.Get()
}

func (m *turboModal) KeyMap() tui.KeyMap {
	if !m.visible.Get() {
		return nil
	}
	return tui.KeyMap{
		tui.OnRuneStop('y', func(ke tui.KeyEvent) {
			m.confirmed.Set(true)
			m.visible.Set(false)
			if m.app != nil {
				m.app.SetInlineHeight(3)
			}
			m.onResult(true)
		}),
		tui.OnRuneStop('n', func(ke tui.KeyEvent) {
			m.visible.Set(false)
			if m.app != nil {
				m.app.SetInlineHeight(3)
			}
			m.onResult(false)
		}),
		tui.OnKeyStop(tui.KeyEscape, func(ke tui.KeyEvent) {
			m.visible.Set(false)
			if m.app != nil {
				m.app.SetInlineHeight(3)
			}
			m.onResult(false)
		}),
	}
}

func (m *turboModal) Render(app *tui.App) *tui.Element {
	var __tui_0 *tui.Element
	if m.visible.Get() {
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithBorder(tui.BorderRounded),
			tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Red)),
			tui.WithPadding(1),
		)
		__tui_2 := tui.New(
			tui.WithText("⚠ Enable Turbo Mode?"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_1.AddChild(__tui_2)
		__tui_3 := tui.New(
			tui.WithText("Turbo mode executes ALL tools without confirmation."),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithText("This includes:"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_4)
		__tui_5 := tui.New(
			tui.WithText("  • File creation, modification, and deletion"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
		)
		__tui_1.AddChild(__tui_5)
		__tui_6 := tui.New(
			tui.WithText("  • Shell command execution"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
		)
		__tui_1.AddChild(__tui_6)
		__tui_7 := tui.New(
			tui.WithText("  • Network requests"),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red)),
		)
		__tui_1.AddChild(__tui_7)
		__tui_8 := tui.New(
			tui.WithText(""),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_8)
		__tui_9 := tui.New(
			tui.WithText("[y] confirm  [n/Esc] cancel"),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_1.AddChild(__tui_9)
		if __tui_0 == nil {
			__tui_0 = __tui_1
		}
	}

	return __tui_0
}

func (m *turboModal) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*turboModal)
	if !ok {
		return
	}
	m.app = f.app
	m.t = f.t
}

var _ tui.PropsUpdater = (*turboModal)(nil)

func (m *turboModal) BindApp(app *tui.App) {
	m.app = app
	if m.visible != nil {
		m.visible.BindApp(app)
	}
	if m.confirmed != nil {
		m.confirmed.BindApp(app)
	}
}

var _ tui.AppBinder = (*turboModal)(nil)
